### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by TineUser** [grammm-dev/gromox#1]
Hi all,

I'm interested in testing Grammm in my home lab. But I don't find any documention about the requirements of Grammm and how to install it.

Can you provide the documentation, please?

Thank You.

**Comment by mrkeksi** [comment]
Whats about that: https://docs.grammm.com/admin/quickstart.html

**Comment by TineUser** [comment]
Thanks to MrKeksi, I got the documentation I didn't find: https://docs.grammm.com/admin/quickstart.html

**Comment by TineUser** [comment]
This documentation is very new (date 01.03.2021) and incomplete. But OK, there is few information where to get the ISO of the appliance.

**Comment by cmpalm** [comment]
This repository is for the Gromox component _only_. Its documentation is in a rather aptly named directory, equally so the install.rst file.
![2](https://user-images.githubusercontent.com/76499379/109655943-286b5180-7b64-11eb-99e4-a04d6478b244.png)
