### ISSUE TITLE
Accessing admin interface

### ISSUE THREAD

**Issue by TineUser** [grammm-dev/gromox#2]
Hi all,

after installing the appliance as virtual machine on my home lab VMware ESXi host and installing nano and open-vm-tools, I now want to start with configuring Grammm. But I can't access the URL https://<IP address>/grammm/admin/interface as it is shown on the console of the appliance.

I get this error:

Die Antwort von <IP address> hat zu lange gedauert
ERR_CONNECTION_TIMED_OUT

I can access the appliance console via SSH. Because of the incomplete documentation I don't know what to do next.

Kind Regards.

**Comment by kaileu** [comment]
You need to run grammm-setup on the cli after you can access the admin panel over http://IP:8080

**Comment by cmpalm** [comment]
This source code repository and issue tracker are for Gromox technical issues only. The admin interface is a separately managed repository, grammm-admin-api and grammm-admin-web.

**Comment by TineUser** [comment]
This is a basic technical issue because im still on the command line level! And the documentation doesn't help to get grammm running.
