### ISSUE TITLE
gromox-imap doesn't advertise STARTTLS capability, but provides it?!

### ISSUE THREAD

**Issue by robert-scheck** [grammm-dev/gromox#3]
As of writing, gromox-imap doesn't advertise the STARTTLS capability, but it still provides it?!

```
$ telnet grammm.net 143
Trying 2a01:4f8:212:3154::2...
Connected to grammm.net.
Escape character is '^]'.
* OK grammm.net service ready
0 CAPABILITY
* CAPABILITY IMAP4rev1 XLIST SPECIAL-USE ID UNSELECT UIDPLUS IDLE AUTH=LOGIN
0 OK CAPABILITY completed
1 STARTTLS
1 OK begin TLS negotiation now
```

_If_ gromox-imap provides STARTTLS support, it should advertise it when requesting the CAPABILITY, otherwise it would make sense to not accept the STARTTLS command either. Note that gromox-pop3 behaves correctly and advertises STLS capability.

**Comment by jengelh** [comment]
This should now be fixed as of https://github.com/grammm-dev/gromox/commit/d96ffbc972dd01e8c6a3bceee197917b976ee877.
