### ISSUE TITLE
IMAP compliance of gromox-imap

### ISSUE THREAD

**Issue by robert-scheck** [grammm-dev/gromox#4]
I would like to suggest to run [ImapTest](https://www.imapwiki.org/ImapTest) against gromox-imap as part of internal tests to address failures such as 'server internal error, midb internal error' (in response to common cases, see e.g. example below) to ensure at basic IMAP standards compliance.

```
$ telnet grammm.net 143
Trying 2a01:4f8:212:3154::2...
Connected to grammm.net.
Escape character is '^]'.
* OK grammm.net service ready
0 LOGIN <snip> <snap>
0 OK logged in
0 CREATE "Abc"
0 OK CREATED completed
0 SELECT "Abc"
0 NO server internal error, midb internal error
0 LIST "" *
* LIST (\HasNoChildren) "/" "INBOX"
* LIST (\HasNoChildren) "/" "Drafts"
* LIST (\HasNoChildren) "/" "Sent Items"
* LIST (\HasNoChildren) "/" "Deleted Items"
* LIST (\HasNoChildren) "/" "Junk E-mail"
0 OK LIST completed
0 DELETE "Abc"
0 OK DELETE completed
0 CREATE "Abc"
0 NO server internal error, midb internal error
```

Interestingly, at this point the folder "Abc" still exists for this user according to grammm web; and if I delete it there, I can re-create it using IMAP. Btw, the IMAP server response should IMHO be "OK CREATE completed" rather "OK CREATED completed".

**Comment by jengelh** [comment]
This should now be fixed with 5f7381d.
