### ISSUE TITLE
Imap Status command failing for folder name with spaces

### ISSUE THREAD

**Issue by mcrainydrop** [grammm-dev/gromox#5]
Hello together,
while trying the Grammm appliance, I encountered a severe bug in the Gromox Imap implementation with respect to the IMAP specification.
By default, the Grammm web interface automatically creates a default folder called "Deleted Items" for trash purpose (which indeed is common default behaviour of mail servers).
When connecting with IMAP, every tested client at first successfully connects, but fails when fetching folder status information.

Here is a raw IMAP log from a connecting client indicating that such a folder with space in its name should be escaped/enclosed in brackets:
17:25:12.377 Imap::Mailbox::NumberOfMessagesTask attached to INBOX Completed
17:25:12.389 <<< * STATUS Deleted Items (MESSAGES 0 UNSEEN 0 RECENT 0)
17:25:12.389 <<< * STATUS Deleted Items (MESSAGES 0 UNSEEN 0 RECENT 0)  8 OK STATUS completed
17:25:12.389 UnexpectedHere Could not parse list: expected a list enclosed in (), but got something else instead
17:25:12.389 Imap::Mailbox::NumberOfMessagesTask attached to Deleted Items Failed: Going offline

I like very much the idea of Grammm as an promising alternative for Exchange, but IMAP is a major requirement and established mail protocol. 
I'm looking forward for an answer and progress in the entire development of Grammm!

----

I'm aware, this is not related to Gromox development. But another aspect I encountered while testing the appliance is, that the Gromox-Imap configuration, which is prepared by the Appliance configuration, is wrong. In the configuration file the config directive "imap_support_stls" is prepared, but from looking in the source code of the Gromox-Imap module, this very directive should be called "imap_support_starttls".
It seems, that these two possibilities doesn't fit to each other.

Where can I post/send to such appliance issues I encountered??

Thank you very much for your support and your great work with Grammm!

**Comment by jengelh** [comment]
This should be fixed as of 43121ec7 .
As for STLS, that was #3 .

**Comment by jengelh** [comment]
There is https://community.grammm.com/ too if an issue is not tied to any particular git repo.
